### ISSUE TITLE
Docs need updated certificate

### ISSUE THREAD

**Issue by Michael-F-Bryan** [daboross/fern-rs#11]
It looks like the cert for your website expired on the 23rd because every time I try to read the [fern docs][docs] chromium shows the "Your connection is not private" message (`NET::ERR_CERT_DATE_INVALID`). 

[docs]: https://dabo.guru/rust/fern/

**Comment by daboross** [comment]
Thanks, seems I thought I had it auto-renewing when it was not. New cert uploaded!
