### ISSUE TITLE
Log crate

### ISSUE THREAD

**Issue by gareins** [daboross/fern-rs#4]
I have been using this crate without

    log = "*"

inside Cargo.toml. Well, it still worked up to a point, that where rustc complained that there was no *log::LogLevelFilter* inside *log* crate. If you could add this detail to crate documentation, it would be great.

I know, there is a dependancy on log 0.2.5, but somehow I had to manually add it into Cargo.toml.

Gareins

**Comment by daboross** [comment]
Hi, I'll be sure to add this - the documentation for fern 0.2.0 did kind of miss that. Thanks!
